name: golden_impact_runner
description: Detect which Flutter Golden Tests are affected by code changes.
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  path: ^1.9.0
  analyzer: ^7.0.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.0

executables:
  golden_impact_runner: golden_impact_runner
